"""Initial migration

Revision ID: 7152c234d9cb
Revises: 
Create Date: 2026-01-01 17:18:01.411312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7152c234d9cb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_logs', sa.Column('log_metadata', sa.JSON(), nullable=True))
    op.drop_column('activity_logs', 'metadata')
    op.alter_column('admins', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'admin'::character varying"))
    op.alter_column('admins', 'permissions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_foreign_key(None, 'crypto_wallets', 'users', ['assigned_to_user_id'], ['id'])
    op.create_foreign_key(None, 'platform_settings', 'admins', ['updated_by_admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'platform_settings', type_='foreignkey')
    op.drop_constraint(None, 'crypto_wallets', type_='foreignkey')
    op.alter_column('admins', 'permissions',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('admins', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'admin'::character varying"))
    op.add_column('activity_logs', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('activity_logs', 'log_metadata')
    # ### end Alembic commands ###
