"""Update transaction types and add admin fields

Revision ID: 967660d4d641
Revises: ae1977f5aeb4
Create Date: 2026-01-01 22:08:00.712126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '967660d4d641'
down_revision: Union[str, None] = 'ae1977f5aeb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
