"""refactor_structure

Revision ID: b6405edcd1c3
Revises: 967660d4d641
Create Date: 2026-01-01 22:29:29.868563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6405edcd1c3'
down_revision: Union[str, None] = '967660d4d641'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_activity_logs_action'), table_name='activity_logs')
    op.drop_index(op.f('idx_activity_logs_admin'), table_name='activity_logs')
    op.drop_index(op.f('idx_activity_logs_created_at'), table_name='activity_logs')
    op.drop_index(op.f('idx_activity_logs_user'), table_name='activity_logs')
    op.drop_index(op.f('idx_admins_email'), table_name='admins')
    op.drop_index(op.f('idx_admins_username'), table_name='admins')
    op.drop_index(op.f('idx_commissions_referrer'), table_name='commissions')
    op.drop_index(op.f('idx_commissions_transaction'), table_name='commissions')
    op.drop_index(op.f('idx_crypto_wallets_address'), table_name='crypto_wallets')
    op.drop_index(op.f('idx_crypto_wallets_network'), table_name='crypto_wallets')
    op.drop_index(op.f('idx_notifications_read'), table_name='notifications')
    op.drop_index(op.f('idx_notifications_user'), table_name='notifications')
    op.drop_index(op.f('idx_platform_settings_key'), table_name='platform_settings')
    op.drop_index(op.f('idx_team_members_child'), table_name='team_members')
    op.drop_index(op.f('idx_team_members_parent'), table_name='team_members')
    op.drop_index(op.f('idx_transactions_created_at'), table_name='transactions')
    op.drop_index(op.f('idx_transactions_status'), table_name='transactions')
    op.drop_index(op.f('idx_transactions_type'), table_name='transactions')
    op.drop_index(op.f('idx_transactions_user'), table_name='transactions')
    op.drop_index(op.f('idx_users_phone'), table_name='users')
    op.drop_index(op.f('idx_users_referral_code'), table_name='users')
    op.drop_index(op.f('idx_users_referred_by'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_users_referred_by'), 'users', ['referred_by_user_id'], unique=False)
    op.create_index(op.f('idx_users_referral_code'), 'users', ['referral_code'], unique=False)
    op.create_index(op.f('idx_users_phone'), 'users', ['phone_number'], unique=False)
    op.create_index(op.f('idx_transactions_user'), 'transactions', ['user_id'], unique=False)
    op.create_index(op.f('idx_transactions_type'), 'transactions', ['type'], unique=False)
    op.create_index(op.f('idx_transactions_status'), 'transactions', ['status'], unique=False)
    op.create_index(op.f('idx_transactions_created_at'), 'transactions', ['created_at'], unique=False)
    op.create_index(op.f('idx_team_members_parent'), 'team_members', ['parent_user_id'], unique=False)
    op.create_index(op.f('idx_team_members_child'), 'team_members', ['child_user_id'], unique=False)
    op.create_index(op.f('idx_platform_settings_key'), 'platform_settings', ['setting_key'], unique=False)
    op.create_index(op.f('idx_notifications_user'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('idx_notifications_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('idx_crypto_wallets_network'), 'crypto_wallets', ['network_type'], unique=False)
    op.create_index(op.f('idx_crypto_wallets_address'), 'crypto_wallets', ['wallet_address'], unique=False)
    op.create_index(op.f('idx_commissions_transaction'), 'commissions', ['transaction_id'], unique=False)
    op.create_index(op.f('idx_commissions_referrer'), 'commissions', ['referrer_user_id'], unique=False)
    op.create_index(op.f('idx_admins_username'), 'admins', ['username'], unique=False)
    op.create_index(op.f('idx_admins_email'), 'admins', ['email'], unique=False)
    op.create_index(op.f('idx_activity_logs_user'), 'activity_logs', ['user_id'], unique=False)
    op.create_index(op.f('idx_activity_logs_created_at'), 'activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('idx_activity_logs_admin'), 'activity_logs', ['admin_id'], unique=False)
    op.create_index(op.f('idx_activity_logs_action'), 'activity_logs', ['action_type'], unique=False)
    # ### end Alembic commands ###
